### ISSUE TITLE
Add HTML comment with SHA1 of running code

### ISSUE THREAD

**Issue by turicas** [NAMD/pypln.web#105]
It'll be easier to debug problems on Web interface if we know exactly which version is running, so I propose to add a little comment in the default template with the SHA1 of the running code. It could be made by our `fabfile.py`.

**Comment by fccoelho** [comment]
Good Idea, but wouldn't it be better to use the commit id number? that way we can refer directly to the code.

**Comment by turicas** [comment]
What do you mean by "commit id"? The commit SHA1, as I said? ;)

**Comment by fccoelho** [comment]
I thought you meant  taking the sha1 of the whole code (tarball or something)
;-)

**Comment by turicas** [comment]
Oops, sorry. It was about the commit SHA1 - and if there's a tag on that
commit, it'd be useful to show too.
