### ISSUE TITLE
Demo app it's not working

### ISSUE THREAD

**Issue by klzns** [NAMD/pypln.web#119]
I've tried to use the [Demo](http://demo.pypln.org/) as suggested in the [Quickstart guide](https://github.com/NAMD/pypln.web/wiki/Quickstart-guide), but I think it's offline.

**Comment by flavioamieiro** [comment]
Thank you very much for the report. I've fixed this in 73aa5559.

On a related note, you may want to use [pypln.api](https://github.com/NAMD/pypln.api), specially if you're already using Python. I'll probably update the quickstart guide to point to it (#120).
