### ISSUE TITLE
Remove requirement of NLTK

### ISSUE THREAD

**Issue by turicas** [NAMD/pypln.web#12]
I think only pypln.backend should have NLTK as a dependency. If we can avoid using NLTK in pypln.web, the deployment process will be more easy and fast.
Currently NLTK is only used in a visualization (wordcloud) to remove stopwords (file `pypln/web/apps/core/visualizations.py`).

**Comment by turicas** [comment]
Related to #14.

**Comment by fccoelho** [comment]
Agreed, so this issue should be moved to the backend, but the permanent storage of  stopword lists (by language, topic, etc) in Mongo needs to be supported ASAP. A lot of analyses depend on this feature.

**Comment by flavioamieiro** [comment]
Since the rewrite we don't need nltk in the frontend anymore.
