### ISSUE TITLE
Remove requirement of flask (and Werkzeug)

### ISSUE THREAD

**Issue by turicas** [NAMD/pypln.web#13]
I think we only used it when we were developing pypln-monitor, but maybe the best place to put it is at pypelinin repository.
So, I think we should remove flask (and Werkzeug) as a dependency of this project.

**Comment by turicas** [comment]
Related to #14.

**Comment by fccoelho** [comment]
At some point, the development of Pypln Monitor will have to be resumed.
But for now I agree that it can be disassociated from this package.

On Fri, Dec 14, 2012 at 12:21 PM, Álvaro Justen notifications@github.comwrote:

> I think we only used it when we were developing pypln-monitor, but maybe
> the best place to put it is at pypelinin repository.
> So, I think we should remove flask (and Werkzeug) as a dependency of this
> project.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/NAMD/pypln.web/issues/13.

## 

# Flávio Codeço Coelho

+55(21) 3799-5567
Professor
Escola de Matemática Aplicada
Fundação Getúlio Vargas
Praia de Botafogo, 190 sala 312
Rio de Janeiro - RJ
22250-900
Brasil
