### ISSUE TITLE
200 code response uploading files in https://fgv.pypln.org/

### ISSUE THREAD

**Issue by renatofcorrea** [NAMD/pypln.web#139]
Why did I get 200 code response using code from Get Started?
So, no file was uploaded. : (
# The corpus url comes from the last response

corpus_url = response.json()['url']
data = {'corpus': corpus_url}

for filename in glob.glob('pdfs/*.pdf'):
    print('Sending {}...'.format(filename))
    with open(filename, 'r') as fp:
        files = {'blob': fp}
        resp = requests.post('http://fgv.pypln.org/documents/', data=data,
            files=files, auth=credentials)
        print(resp.status_code)

**Comment by flavioamieiro** [comment]
@renatofcorrea I've managed to reproduce this bug. As soon as I have a fix for it I'll document it here.

Thank you for reporting this.

**Comment by flavioamieiro** [comment]
I think I may have found the problem: if we use 'http://fgv.pypln.org/corpora/<corpus_id>/' (with `http` instead of `https`) as the corpus URL, we get a 200 response. This is probably due to a redirect from `http` to `https` somewhere along the request. 

@renatofcorrea could you please try using 'https' in both the `corpus_url` and the `requests.post` call?

**Comment by flavioamieiro** [comment]
Ok, some more documentation on this: apparently [it is common for browsers to turn POST requests into GET requests after a redirect](https://curl.haxx.se/docs/manpage.html#--post301). I can confirm that running the following request will hit the bug (i.e: return 200 and not create the document):

```
curl --user <username>:<password> -F blob=@file.txt -F corpus=https://fgv.pypln.org/corpora/<corpus_id>/ http://fgv.pypln.org/documents/  --location
```

while running the same request with `--post301` (which instructs curl not to turn POST requests into GETs) will work:

```
curl --user <username>:<password> -F blob=@file.txt -F corpus=https://fgv.pypln.org/corpora/<corpus_id>/ http://fgv.pypln.org/documents/  --post301 --location
```

I'm looking into how to tell `requests` to behave the same way, but for now I think using 'https' in all urls should work around the problem.
