### ISSUE TITLE
Create visualizations for bigrams/trigrams

### ISSUE THREAD

**Issue by fccoelho** [NAMD/pypln.web#18]
After the bigram/trigram worker get merged, we need to work on having a visualization for it.

There are many ways to consume bigrams/trigrams (collocations). For some examples available on nltk, see this link:
http://nltk.googlecode.com/svn/trunk/doc/howto/collocations.html

This means we will have to provide a reasonably complex api for downloading  the results. We should discuss this in more detail before specifying.

an alternative would be to provide an all-inclusive csv with results:
http://wordhoard.northwestern.edu/userman/images/findmwuoutput2.jpg
Maybe I can modify the workers to store this CSV directly as a result, instean of the pickle of the finder...

For the visualization, the interface will have to reflect the options available in NLTK. I'll propose a design mockup in a comment to this issue briefly.

example visualizations:
- http://www.chrisharrison.net/index.php/Visualizations/WordSpectrum
- http://bl.ocks.org/4063269

**Comment by flavioamieiro** [comment]
PyPLN has evolved to be mostly an API, and we don't have visualizations anymore so I'll close this.
