### ISSUE TITLE
Fix update_index exception

### ISSUE THREAD

**Issue by turicas** [NAMD/pypln.web#19]
I'm working on the [feature/full-text-search](https://github.com/turicas/pypln.web/tree/feature/full-text-search) branch and there is an exception being raised after the execution of `Command.handler`:

```
Exception AttributeError: "'NoneType' object has no attribute 'getpid'" in <bound method GridFSStorage.__del__ of <core.storage.GridFSStorage object at 0x3f1e690>> ignored
```

As we are not using `GridFSStorage` in this command and all operations are being executed successfully, there is no problem (in terms of functioning), but it's a good idea to search for the problem and fix it so the exception is not shown when the command is executed.

**Comment by flavioamieiro** [comment]
I agree with you, but I just wanted to point out that we _are_ using GridFSStorage. Every time we instantiate a Document, you're touching GridFSStorage. In any case, this is a really weird bug.

**Comment by flavioamieiro** [comment]
I'll close this issue because we are no longer using this implementation of full text search.
