### ISSUE TITLE
Pagination for documents and analytical results

### ISSUE THREAD

**Issue by fccoelho** [NAMD/pypln.web#22]
@flavioamieiro : we need to paginate (with fetching on demand) the presentation of documents on the web other wise the site will become absurdly slow. Please check the 6.8MB PDF I added in the demo account.

**Comment by flavioamieiro** [comment]
I agree with you. We had already noticed that with a large document, the Part-of-speech tagging view was slow, so this is really a much needed feature.

**Comment by flavioamieiro** [comment]
Does anyone have a suggestion about which approach would be best here? @turicas?

**Comment by turicas** [comment]
We can paginate by number of tokens and use AJAX to load new pages.

**Comment by fccoelho** [comment]
I think django has support for paginations
