### ISSUE TITLE
Slugs should always be slugs, or they should not exist!

### ISSUE THREAD

**Issue by flavioamieiro** [NAMD/pypln.web#40]
We're [generating file slugs when saving them](https://github.com/NAMD/pypln.web/blob/develop/pypln/web/apps/core/models.py#L62). This works great, but if a filename is not a proper slug (if it has spaces, for example), this code will always generate the same slug, because it will still be available in the backend (since the backend was smart enough to slugify the filename before saving).

The fix for this looks simple enough: just slugify the filename before asking the storage for an available name, and it should be ok. But I think this stresses another point: do we _need_ file slugs? I think it should be much easier to just refer to the file by it's id. As a con, the urls wouldn't have the file name but this shouldn't have much of an impact on the usability (they are already weird because of the suffix we add to them). As a pro, we'd have much less code to write, much more consistency, and the user wouldn't be confused by all those _1.pdf, _2.pdf that appear in their document list (we could just show them the file name, as their file manager does).

@turicas @fccoelho @rsouza what do you think?

Again, thank you @berinhard for finding and reporting this issue. I'm very glad you're helping us!

**Comment by berinhard** [comment]
@flavioamieiro thanks! If there anything else that I can help with let me know.

**Comment by fccoelho** [comment]
Well, @flavioamieiro , you have a good point. If file systems don't need slugs, why should we?

**Comment by turicas** [comment]
@fccoelho to create nice URLs.

I'm against using file id in the URL. Maybe we can have a "private MongoDB file storage" for each user and solve the problem of not repeating files in the store - this way we won't have "*_N.extension" files.

**Comment by flavioamieiro** [comment]
@turicas the id's in the url make sure they point to a unique resource. I don't think urls are less nice because of that. In fact, it's a very common pattern to use id's for URLs.

I do think slugs are important for some kinds of resources. Mainly the ones that need to be indexed by search engines and the like. Our urls are pointing to resources that are not public, thus not indexable by third parties. 

In any case, we can still have both: we can use the id to guarantee the uniqueness of the URL, and compose that with the filename, so we still have it in the url. In this case a document resource would look something like: `http://demo.pypln.org/document/1/filename.pdf`, and if there was another file with the same filename, we'd have `http://demo.pypln.org/document/42/filename.pdf`.

That being said, I think we should sit down to discuss our URL map in a more sustainable way. It has grown organically until now, but this will be much more important in the process of building our REST API. There is no good REST API without good, semantic URLs. And for that, we need to define the role of the entities in the system. For example: maybe a document only makes sense inside a corpus. If that's the case, the URL for the document should probably include the corpus in which it resides: `http://demo.pypln.org/dengue/document/42/filename.pdf`.

I'm not sure this is a good example, but my point is: I don't think the relationship between our entities is well defined (at least not for me), and this reflects badly in our entire codebase (specially our models and urls).

**Comment by flavioamieiro** [comment]
Just to make sure this doesn't derail into the wrong argument: 
- I'm not against slugs
- I'm not a defender of id's
- I don't think that's the point

The point is: there are, as I said in the last paragraphs, a lot of things that needs to be cleared up (at least to me) about our models. That issue has turned up more and more frequent. And if we solve that, maybe we'll have a more sustainable way of building cool urls. 

As an _example_: is there _really_ a possible case of a document with the same filename in the same corpus associated with the same user? If not, having `http://demo.pypln.org/dengue/filename.pdf` (and of course filtering by user) should be enough to make this resource unique, with a cool url (that _maybe_ should include the username, maybe not), and we could use the document id and the name generated by gridfs to refer to them internally.

**Comment by fccoelho** [comment]
@turicas , I think numbers are also nice. 

The problem of file duplication in the store has  nothing to do with the url. We have already discussed this.

**Comment by flavioamieiro** [comment]
I've addressed the more pressing issue of correctly generating the slugs in #41 but I'll leave this issue open since it's broader and has other implications.

**Comment by turicas** [comment]
I think we should rename this issue to something like "create a map/definition of semantic URLs", that's the point here. :-)
We'll need it well defined for the REST API.

**Comment by rhcarvalho** [comment]
#77 shows that there is still a problem when a user uploads (or tries to upload) a file to a corpora that already have it or another file with the same name.

## 

By the way, I've seem "cool" websites using thinks like @flavioamieiro said, `http://demo.pypln.org/document/1/filename.pdf`.

Ah, Gmail nowadays uses URLs like "https://mail.google.com/mail/ca/u/0/?ui=2&shva=1#inbox?compose=13cd8e9eab227a74"
