### ISSUE TITLE
Treat all punctuation as one tag in POS-tagging view

### ISSUE THREAD

**Issue by flavioamieiro** [NAMD/pypln.web#49]
For now, the PALAVRAS worker is returning one tag for each punctuation character, and we try to map it in our tagset, but this means in the visualization we'll have one checkbox (and color) for each punctuation character in the document.

**Comment by turicas** [comment]
We should use this conversion table:

```
# -> #
$ -> $
, -> ,
- -> :
. -> .
: -> :
; -> :
? -> .
` -> ``
```

The other characters on `string.punctuation` are not recognized as punctuation by NLTK.
