### ISSUE TITLE
Wordclud generation on the backend

### ISSUE THREAD

**Issue by fccoelho** [NAMD/pypln.web#55]
By using the code below, we can generate the word clouds in the backend and cache them.

Another alternative would be to have a worker for this...and save the image in the database.

https://github.com/amueller/word_cloud

**Comment by turicas** [comment]
I don't think it's a issue since we are generating the visualization in JavaScript - and in future it'll be possible to link words for visualize wordcloud (or other analyses) filtering by that word. If we use images we won't be able to do it.
@flavioamieiro, what do you think?

**Comment by fccoelho** [comment]
I know, but there is space for vaious types of wordcloud  and this library generates a image much nicer that than the javascript generated one.

Besides, havong a way to generate wordclouds with python allows us to offer this output through the API.

**Comment by flavioamieiro** [comment]
I don't have a strong opinion against generating the cloud in javascript and I liked that the words were text, and not an image. On the other hand, we've seen that when using a slightly larger document (95 pages) it took a noticeable time, so maybe it won't scale very well.

I think that the ability to cache the image and make it available for download through the API is very nice.

**Comment by fccoelho** [comment]
I think the two serve distinct purposes: the javascript one can be interactive allowing the user to explore the freqdist, the Python one, will generate a nice image which the user can use in a publication, for example.

It can even be calculated locally on the user's machine if he/she is using the API.
