### ISSUE TITLE
Unify pypln.web requirements

### ISSUE THREAD

**Issue by rhcarvalho** [NAMD/pypln.web#67]
Currently there are requirement files in two levels:

```
.
├── web
│     ├── requirements
│     │   ├── base.txt
│     │   └── project.txt
...
└── requirements
      ├── development.txt
      └── production.txt
```

The requirements have overlapping entries and it is not very clear which ones are to be used.

The project level README.rst refers to requirements/development.txt and requirements/production.txt.

**Comment by rhcarvalho** [comment]
Just noticed how one file requires "django" and the other requires "Django==1.3.1", which made me download django twice (the newest version to date and 1.3.1).

**Comment by turicas** [comment]
Duplicated #14.
