### ISSUE TITLE
Remove Pinax from the project

### ISSUE THREAD

**Issue by flavioamieiro** [NAMD/pypln.web#70]
As the project is right now, we're not using many of Pinax's features. On the other hand, it introduces a lot of complexity to the project. I think, right now, we can replace Pinax with Django's built-in auth app and a small profile model.

**Comment by flavioamieiro** [comment]
It looks like these are the parts of Pinax we are actually using:
- Their extensions to django's built-in auth app.
- OpenID authentication (in demo.pypln.org there are 5 users using openid to login)
- A Profile app (which is there, but as far as I have seen no one has used it;  this doesn't seem like an important feature)
- The bootstrap theme

It looks like the biggest problem in removing Pinax from the project will be replacing OpenID authentication. 
Their modifications to the built-in auth app (apart from connecting the openid app) add things we don't use (like anonymous accounts). 
The profile app could be removed or replaced with our own (which should be simpler than maintaining Pinax on the project) or using idios (which is what Pinax uses).
The bootstrap theme could be replaced by our own templates (which should be _a lot_ simpler than the ones Pinax forces us to create) and just using bootstrap (this would even have the benefit of allowing us to update bootstrap).

With regards to OpenID, I think our choices are: 
- drop it (and break demo.pypln.org for the 5 people that use it)
- use the same app Pinax uses for OpenID (even though it is just a package on pypi with no other information, and the project with the same name on github states that it is not complete)
- use another app to support OpenID (which seems the more robust solution, even though finding the right app will probably take some work, unless someone has experience with this).

@turicas @fccoelho @rhcarvalho what are your opinions on this?

**Comment by turicas** [comment]
I think we can send a message to these 5 users and drop OpenID support for now.
About the theme, we maybe use [foundation](http://foundation.zurb.com/) instead of bootstrap (I used it on pypln.org).

**Comment by fccoelho** [comment]
OpenID can be a pain in the neck, but is relevant to reduce the hassle of using the system. I agree with @turicas  regarding warning the users, but I think we should bring back openID as soon as possible. 
I think we should stick to bootstrap since it is not by itself causing us any problems.
