### ISSUE TITLE
Verify why gunicorn is using too much CPU

### ISSUE THREAD

**Issue by turicas** [NAMD/pypln.web#83]
I've created a script using [pypln.api](https://github.com/NAMD/pypln.api) to upload thousands of PDFs to demo.pypln.org and, as it was taking a lot of time, I checked `htop` in the server... one of the reasons to this long time to upload is the lack of pagination in corpus page, but I found that gunicorn was using ~80% of CPU most of the time.
We need to check it, try to solve or replace gunicorn for a lighter alternative.

**Comment by fccoelho** [comment]
I don't think I understood... If you are uploading through the api What
does the pagination of the corpus view have to do with it?

I any case, we need to develop a stress testing routine which can be
applied to PyPLN on a regular basis to avoid  these kind of problems.

On Thu, Feb 21, 2013 at 3:22 PM, Álvaro Justen notifications@github.comwrote:

> I've created a script using pypln.api https://github.com/NAMD/pypln.apito upload thousands of PDFs to
> demo.pypln.org and, as it was taking a lot of time, I checked htop in the
> server... one of the reasons to this long time to upload is the lack of
> pagination in corpus page, but I found that gunicorn was using ~80% of CPU
> most of the time.
> We need to check it, try to solve or replace gunicorn for a lighter
> alternative.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/NAMD/pypln.web/issues/83.

## 

# Flávio Codeço Coelho

+55(21) 3799-5567
Professor
Escola de Matemática Aplicada
Fundação Getúlio Vargas
Praia de Botafogo, 190 sala 312
Rio de Janeiro - RJ
22250-900
Brasil

**Comment by turicas** [comment]
The curruent API needs to do scraping in the web interface. To upload a new document, it needs to get the Django CSRF token in the corpus page (which is the same page that lists the documents). To check if the document was uploaded successfully, it needs to get (again) the corpous page to verify if the document is in the list (and to get some information about the document).

But independent of this (this is _another issue_), we figured out that gunicorn is using too much CPU. So this issue is to verify why it's happening, if is there a way to optimize it or if is it better to change to another software.
