### ISSUE TITLE
Optimize uploads

### ISSUE THREAD

**Issue by turicas** [NAMD/pypln.web#88]
Currently we have upload rates near 2 documents/second. It's really bad, because our cluster with only 3 machines can process way more than it (I'm doing a test and lots of workers are idle).
We need to check all bottlenecks in the process of uploading documents (one or more than one per POST).
Probably one bottleneck is the act of creating a new connection to PyPLN's router on every POST request. One solution is to store the document in the database with a flag `sent_to_backend = False` and have a cronjob or daemon that sends all documents with this flag (then, set it to `True`).

**Comment by flavioamieiro** [comment]
There is a new issue for this #118
