### ISSUE TITLE
Bring back full text search

### ISSUE THREAD

**Issue by flavioamieiro** [NAMD/pypln.web#94]
After the rewrite we need to bring back full text search capabilities to the web interface. We should probably use a more robust solution than whoosh (at least in the way we were using it). Any suggestions?

**Comment by fccoelho** [comment]
I think the best candidate, for the features it has is Solr, but careful
thought should be given as to how best to integrate it into our
infrastructure.

On Wed, Oct 2, 2013 at 7:18 AM, Flávio Amieiro notifications@github.comwrote:

> After the rewrite we need to bring back full text search capabilities to
> the web interface. We should probably use a more robust solution than
> whoosh (at least in the way we were using it). Any suggestions?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/NAMD/pypln.web/issues/94
> .

## 

# Flávio Codeço Coelho

+55(21) 3799-5551
Professor
Escola de Matemática Aplicada
Fundação Getulio Vargas
Praia de Botafogo, 190 sala 312
Rio de Janeiro - RJ
22250-900
Brasil

**Comment by turicas** [comment]
We still need to decide about what search engine to use. [Techu](http://georgepsarakis.github.io/techu-search-server/) may help (uses Sphinx).

**Comment by fccoelho** [comment]
This techu seems very interesting. But it doesn't provide faceting, we
could integrate a faceting python library, but it would take time. I think
we should consider solr, connected directly to mongodb via mongoconnector:
http://blog.mongodb.org/post/29127828146/introducing-mongo-connector

On Mon, Nov 11, 2013 at 6:07 AM, Álvaro Justen notifications@github.comwrote:

> We still need to decide about what search engine to use. Techuhttp://georgepsarakis.github.io/techu-search-server/may help (uses Sphinx).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/NAMD/pypln.web/issues/94#issuecomment-28180182
> .

## 

# Flávio Codeço Coelho

+55(21) 3799-5551
Professor
Escola de Matemática Aplicada
Fundação Getulio Vargas
Praia de Botafogo, 190 sala 312
Rio de Janeiro - RJ
22250-900
Brasil
